manifest:
  defaults:
    revision: main
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: cr3eperall
      url-base: https://github.com/cr3eperall
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-feature-hall-effect
      remote: cr3eperall
  self:
    path: config
